# Generated by Django 4.0.4 on 2022-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='os_profile_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
