# Generated by Django 4.0.4 on 2022-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_fooditem_user_fooditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.CharField(blank=True, choices=[('gain', 'Gain'), ('lose', 'Lose')], max_length=10, null=True),
        ),
    ]
